// web/src/components/records/RecordEditModal.tsx
import { App, Form, Input, InputNumber, Modal, Select } from 'antd'
import i18n from '../../locale'
import { AAAARecord, ARecord, CAARecord, CNAMERecord, MXRecord, NSRecord, Record, RecordTypes, SRVRecord, TXTRecord } from '../../stores/records'
import { useEffect, useState } from 'react'
import { CheckOutlined, CloseOutlined } from '@ant-design/icons'
import { ResponseError, getErrorInfo } from '../../api'
import { FormInstance } from 'antd/lib/form/Form'
const { t } = i18n

type Props = {
    open: boolean
    record: Record
    //domain: string
    onCancel(): void
    onOk(): void

    editRecord(record: Record): Promise<void>
    createRecord(record: Record): Promise<void>
}

const recordTypeOptions = Object.entries(RecordTypes).filter(e => e[1] !== RecordTypes.RecordTypeSOA).map(e => {
    return {
        value: e[1],
        label: e[1]
    }
})

export default function RecordEditModal({ open, record, onOk, onCancel, editRecord, createRecord }: Props) {
    const [loading, setLoading] = useState(false)
    const [form] = Form.useForm<Record>()
    const { notification } = App.useApp()

    useEffect(() => { form.setFieldsValue(record) }, [open])

    async function confirm() {
        const commitFunction = (!record.id || record.id < 1) ? createRecord : editRecord
        setLoading(true)
        try {
            record = await form.validateFields()
            await commitFunction(record)
            onOk()
        } catch (error) {
            const msg = getErrorInfo(error as ResponseError)
            notification.error(msg)
            console.error(error)
        } finally {
            setLoading(false)
        }
    }

    const controls = new Map<RecordTypes, (f: FormInstance<Record>) => JSX.Element>([
        [
            RecordTypes.RecordTypeA, (
                ({ getFieldValue }) =>
                    <Form.Item<Record<ARecord>> label='IP' name={['content', 'ip']} required rules={[{
                        validator() {

                            const result = ARecord.validate(getFieldValue('content') as ARecord)
                            return (result === true) ? Promise.resolve() : Promise.reject(result)
                        }
                    }]}>
                        <Input />
                    </Form.Item>
            )
        ],
        [
            RecordTypes.RecordTypeAAAA, (
                ({ getFieldValue }) =>
                    <Form.Item<Record<AAAARecord>> label='IP' name={['content', 'ip']} required rules={[{
                        validator() {
                            const result = AAAARecord.validate(getFieldValue('content') as AAAARecord)
                            return (result === true) ? Promise.resolve() : Promise.reject(result)
                        }
                    }]}>
                        <Input />
                    </Form.Item>
            )
        ],
        [
            RecordTypes.RecordTypeCNAME, (
                ({ getFieldValue }) =>
                    <Form.Item<Record<CNAMERecord>> label={t('records.form.host')} required name={['content', 'host']}
                        rules={[{
                            validator() {
                                const result = CNAMERecord.validate(getFieldValue('content') as CNAMERecord)
                                return (result === true) ? Promise.resolve() : Promise.reject(result)
                            }
                        }]}>
                        <Input />
                    </Form.Item>
            )
        ],
        [
            RecordTypes.RecordTypeNS, (
                ({ getFieldValue }) =>
                    <Form.Item<Record<NSRecord>> label={t('records.form.host')} name={['content', 'host']} required
                        rules={[{
                            validator() {
                                const result = NSRecord.validate(getFieldValue('content') as NSRecord)
                                return (result === true) ? Promise.resolve() : Promise.reject(result)
                            }
                        }]}>
                        <Input />
                    </Form.Item>
            )
        ],
        [
            RecordTypes.RecordTypeTXT, (
                ({ getFieldValue }) =>
                    <Form.Item<Record<TXTRecord>> label={t('records.form.text')} name={['content', 'text']} required
                        rules={[{
                            validator() {
                                const result = TXTRecord.validate(getFieldValue('content') as TXTRecord)
                                return (result === true) ? Promise.resolve() : Promise.reject(result)
                            }
                        }]}>
                        <Input />
                    </Form.Item>
            )
        ],
        [
            RecordTypes.RecordTypeMX, (
                ({ getFieldValue }) =>
                    <>
                        <Form.Item<Record<MXRecord>> label={t('records.form.host')} name={['content', 'host']} required
                            rules={[{
                                validator() {
                                    const result = MXRecord.validate(getFieldValue('content') as MXRecord)
                                    return (result === true) ? Promise.resolve() : Promise.reject(result)
                                }
                            }]}>
                            <Input />
                        </Form.Item>
                        <Form.Item<Record<MXRecord>> label={t('records.form.preference')} name={['content', 'preference']} required>
                            <InputNumber controls={false} />
                        </Form.Item>
                    </>
            )
        ],
        [
            RecordTypes.RecordTypeCAA, (
                ({ getFieldValue }) =>
                    <>
                        <Form.Item<Record<CAARecord>> label={t('records.form.flag')} name={['content', 'flag']} required>
                            <InputNumber controls={false} />
                        </Form.Item>
                        <Form.Item<Record<CAARecord>> label={t('records.form.tag')} name={['content', 'tag']} required rules={[{
                            validator() {
                                const result = CAARecord.validate(getFieldValue('content') as CAARecord)
                                return (result === true) ? Promise.resolve() : Promise.reject(result)
                            }
                        }]}>
                            <Input />
                        </Form.Item>
                        <Form.Item<Record<CAARecord>> label={t('records.form.value')} name={['content', 'value']} required rules={[
                            { required: true, message: t('common.mandatory') }
                        ]} >
                            <Input />
                        </Form.Item>
                    </>
            )
        ],
        [
            RecordTypes.RecordTypeSRV, (
                ({ getFieldValue }) =>
                    <>
                        <Form.Item<Record<SRVRecord>> label={t('records.form.priority')} name={['content', 'priority']} required>
                            <InputNumber controls={false} />
                        </Form.Item>

                        <Form.Item<Record<SRVRecord>> label={t('records.form.weight')} name={['content', 'weight']} required>
                            <InputNumber controls={false} />
                        </Form.Item>

                        <Form.Item<Record<SRVRecord>> label={t('records.form.port')} name={['content', 'port']} required>
                            <InputNumber controls={false} />
                        </Form.Item>

                        <Form.Item<Record<SRVRecord>> label={t('records.form.target')} name={['content', 'target']} required rules={[{
                            validator() {
                                const result = SRVRecord.validate(getFieldValue('content') as SRVRecord)
                                return (result === true) ? Promise.resolve() : Promise.reject(result)
                            }
                        }]}>
                            <Input />
                        </Form.Item>
                    </>
            )
        ]
    ])

    return (
        <Modal
            onCancel={onCancel} onOk={confirm}
            title={
                <span>
                    {
                        (!record || !record.id || record.id < 1) ? t('common.new') : t('common.edit')
                    }
                    {
                        t('records._')
                    }
                </span>
            }
            confirmLoading={loading}
            cancelButtonProps={{
                icon: <CloseOutlined />,
            }}
            okButtonProps={{
                icon: <CheckOutlined />,
                htmlType: 'submit'
            }}

            open={open}
            closeIcon={false}
            maskClosable={false}

            centered
            destroyOnClose
            forceRender
        >
            <Form<Record> name='record' form={form}
                scrollToFirstError
                autoComplete='off'
                labelCol={{ span: 4 }}
                wrapperCol={{ span: 20 }}
                validateTrigger='onBlur'
            >
                <Form.Item<Record> label={t('records.recordType')} required name='record_type'>
                    <Select allowClear={false} options={recordTypeOptions} />
                </Form.Item>
                <Form.Item<Record> label={t('records.name')} required name='name' rules={[
                    {
                        validator(_rule, value) {
                            const result = Record.validateName(value)
                            return (result === true) ? Promise.resolve() : Promise.reject(result)
                        },
                    }
                ]}>
                    <Input />
                </Form.Item>
                <Form.Item<Record> label='TTL' required name='ttl'>
                    <InputNumber controls={false} addonAfter={t('common.unitForSecond')} />
                </Form.Item>
                <Form.Item<Record> noStyle shouldUpdate={(p, c) => p.record_type !== c.record_type}>
                    {
                        ({ getFieldValue }: FormInstance<Record>) => {
                            const e = controls.get(getFieldValue('record_type'))
                            if (!e) {
                                return <></>
                            }
                            return e({ getFieldValue } as FormInstance<Record>)
                        }
                    }
                </Form.Item>
            </Form>
        </Modal>
    )
}

// web/src/components/records/RecordEditModal.vue
<template>
    <NModal :mask-closable="false" :show="show">
        <NCard style="width: 640px" role="dialog" aria-modal="true">
            <template #header>
                <span v-if="!record || !record.id || record.id < 1">{{ t('common.new') }}</span><span v-else>{{
                    t('common.edit') }}</span><span>{{ t('records._') }}</span>
            </template>

            <NForm :model="record" inline :rules="rules">
                <NFormItem :label="t('records.recordType')">
                    <NSelect v-model:value="record.record_type" :options="recordTypeOptions" />
                </NFormItem>
                <NFormItem :label="t('records.name')" path="name">
                    <NInput v-model:value="record.name" />
                </NFormItem>
                <NFormItem label="TTL" path="ttl">
                    <NInputNumber v-model:value="record.ttl" :show-button="false">
                        <template #suffix>
                            {{ t('common.unitForSecond') }}
                        </template>
                    </NInputNumber>
                </NFormItem>
            </NForm>
            <NForm :model="record" inline>
                <NFormItem :label="t('records.content')"
                    v-if="[RecordTypes.RecordTypeA, RecordTypes.RecordTypeAAAA].indexOf(record.record_type) > -1">
                    <NInput v-model:value="(record.content as ARecord | AAAARecord).ip" placeholder="IP" />
                </NFormItem>
                <NFormItem :label="t('records.content')"
                    v-if="[RecordTypes.RecordTypeCNAME, RecordTypes.RecordTypeNS].indexOf(record.record_type) > -1">
                    <NInput v-model:value="(record.content as CNAMERecord | NSRecord).host"
                        :placeholder="t('records.form.host')" />
                </NFormItem>
                <NFormItem :label="t('records.content')" v-if="RecordTypes.RecordTypeTXT === record.record_type">
                    <NInput v-model:value="(record.content as TXTRecord).text" :placeholder="t('records.form.text')" />
                </NFormItem>
                <NFormItem :label="t('records.content')" v-if="RecordTypes.RecordTypeMX === record.record_type">
                    <NInputGroup>
                        <NInput :placeholder="t('records.form.host')" v-model:value="(record.content as MXRecord).host"
                            style="width: 75%;" />
                        <NInputNumber :placeholder="t('records.form.preference')"
                            v-model:value="(record.content as MXRecord).preference" style="width: 25%;" />
                    </NInputGroup>
                </NFormItem>
                <NFormItem :label="t('records.content')" v-if="RecordTypes.RecordTypeSRV === record.record_type">
                    <NInputGroup>
                        <NInputNumber :placeholder="t('records.form.priority')"
                            v-model:value="(record.content as SRVRecord).priority" style="width: 25%;" />
                        <NInputNumber :placeholder="t('records.form.weight')"
                            v-model:value="(record.content as SRVRecord).weight" style="width: 25%;" />
                        <NInputNumber :placeholder="t('records.form.port')"
                            v-model:value="(record.content as SRVRecord).port" style="width: 25%;" :min="0"
                            :max="65535" />
                        <NInput :placeholder="t('records.form.target')"
                            v-model:value="(record.content as SRVRecord).target" style="width: 25%;" />
                    </NInputGroup>
                </NFormItem>
                <NFormItem :label="t('records.content')" v-if="RecordTypes.RecordTypeCAA === record.record_type">
                    <NInputGroup>
                        <NInputNumber :placeholder="t('records.form.flag')"
                            v-model:value="(record.content as CAARecord).flag" style="width: 20%;" />
                        <NInput :placeholder="t('records.form.tag')" v-model:value="(record.content as CAARecord).tag"
                            style="width: 40%;" />
                        <NInput :placeholder="t('records.form.value')"
                            v-model:value="(record.content as CAARecord).value" style="width: 40%;" />
                    </NInputGroup>
                </NFormItem>
            </NForm>

            <template #action>
                <NFlex justify="end">
                    <NButton size="small" @click="show = false">
                        <template #icon>
                            <NIcon>
                                <Times />
                            </NIcon>
                        </template>
                        {{ t('common.cancel') }}
                    </NButton>

                    <NButton size="small" type="primary" :loading="loading" @click="confirm" attr-type="submit">
                        <template #icon>
                            <NIcon>
                                <Check />
                            </NIcon>
                        </template>
                        {{ t('common.confirm') }}
                    </NButton>
                </NFlex>
            </template>
        </NCard>
    </NModal>
</template>

<script setup lang="ts">
import {
    NModal,
    NCard,
    NForm,
    NFormItem,
    NFlex,
    NButton,
    NInput,
    NInputNumber,
    NInputGroup,
    NSelect,
    useNotification,
    type FormRules,
    type SelectOption
} from 'naive-ui'
import { getErrorInfo } from '@/apis/api';
import {
    useRecordStore,
    RecordTypes,
    type Record,
    type ARecord,
    type AAAARecord,
    type CAARecord,
    type CNAMERecord,
    type NSRecord,
    type SRVRecord,
    type TXTRecord,
    type MXRecord,
} from '@/stores/records';
import { Check, Times } from '@vicons/fa';
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';
const { t } = useI18n()
const props = defineProps<{
    record: Record,
    domain: string,
}>()

const show = defineModel<boolean>('show', { default: false })
const loading = ref(false)
const notification = useNotification()
const recordStore = useRecordStore()
const recordTypeOptions = Object.entries(RecordTypes).filter(
    e => e[1] !== RecordTypes.RecordTypeSOA
).map(e => {
    return {
        label: e[1],
        value: e[1]
    } as SelectOption
})
const rules = {
    name: {
        required: true,
        trigger: 'blur',
        message: t('common.mandatory')
    }
} as FormRules

async function confirm() {
    loading.value = true;
    try {
        if (!props.record.id || props.record.id < 1) {
            await recordStore.addRecord(props.domain, props.record)
        } else {
            await recordStore.updateRecord(props.domain, props.record)
        }
        show.value = false
    } catch (e) {
        const msg = getErrorInfo(e)
        notification.error(msg)
        console.error(e)
    }
    loading.value = false;
}
</script>
